
@url = http://localhost:8080/api/v1

GET {{url}}/opening
Content-Type: application/json

###
POST {{url}}/opening
Content-Type: application/json

{
  "role": "Software Engineer",
  "company": "Tech Innovators Inc.",
  "location": "San Francisco, CA",
  "isRemote": true,
  "link": "www.jobs.com/software-engineer",
  "salary": 120000
}

###

GET {{url}}/opening/1
Content-Type: application/json

###
DELETE  {{url}}/opening/1
Content-Type: application/json